export const ConditionAnimation = {
    'Partly cloudy': require('../assets/animations/partaillyCloud.json'),
    'Moderate rain': require('../assets/animations/lightRain.json'),
    'Patchy rain possible': require('../assets/animations/lightRain.json'),
    'Sunny': require('../assets/animations/sun.json'),
    'Clear': require('../assets/animations/sun.json'),
    'Overcast': require('../assets/animations/cloud.json'),
    'Cloudy': require('../assets/animations/cloud.json'),
    'Light rain': require('../assets/animations/lightRain.json'),
    'Light rain shower': require('../assets/animations/rainWithShower.json'),
    'Moderate rain at times': require('../assets/animations/lightRain.json'),
    'Heavy rain': require('../assets/animations/heavyRain.json'),
    'Heavy rain at times': require('../assets/animations/heavyRain.json'),
    'Moderate or heavy freezing rain': require('../assets/animations/heavyRain.json'),
    'Moderate or heavy rain shower': require('../assets/animations/heavyRain.json'),
    'Moderate or heavy rain with thunder': require('../assets/animations/rainWithThunder.json'),
    'Thundery outbreaks possible': require('../assets/animations/rainWithThunder.json'),
    'Mist': require('../assets/animations/fog.json'),
    'Fog': require('../assets/animations/fog.json'),
    'other': require('../assets/animations/sun.json'),
}